name: Bazel

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: ubuntu-latest
          cxxopt: -std=c++17
        - platform: macos-latest
          cxxopt: -std=c++17
        - platform: windows-latest
          cxxopt: /std:c++17

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Cache Setup
      uses: actions/cache@v4
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel

    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: 'latest'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: >
        bazel build
        --cxxopt=${{matrix.cxxopt}}
        --disk_cache=~/.cache/bazel
        //...

    - name: Test
      run: >
        bazel test
        --cxxopt=${{matrix.cxxopt}}
        --disk_cache=~/.cache/bazel
        //...
