name: Bazel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache Setup
      uses: actions/cache@v4
      id: cache-bazel
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel

    - name: Setup bazel
      uses: jwlawson/actions-setup-bazel@v2
      with:
        bazel-version: 'latest'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: >
        bazel build
        --disk_cache=~/.cache/bazel
        //...

    - name: Test
      run: >
        bazel test
        --disk_cache=~/.cache/bazel
        //...
